server:
  port: 8080

spring:
  application:
    name: spring-cloud-servicecomb
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-east-2.myhuaweicloud.com
        serviceName: spdemo
        version: 0.0.1
        healthCheckInterval: 30
        autoDiscovery: true